//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Users/admin/github/clojure-objc-sample/jvm/objc/NativeFunctions.java
//
//  Created by admin on 1/26/14.
//

#ifndef _ObjcNativeFunctions_H_
#define _ObjcNativeFunctions_H_

@interface NativeFunctions : NSObject {
}

+ (float)cgrectx:(id)cgrect;
+ (float)cgrecty:(id)cgrect;
+ (float)cgrectw:(id)cgrect;
+ (float)cgrecth:(id)cgrect;
+ (id)cgrectmake:(float)x
                y:(float)y
                w:(float)w
                h:(float)h;
- (id)init;
@end

#endif // _ObjcNativeFunctions_H_
