//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Users/admin/github/clojure-objc-sample/jvm/objc/NativeFunctions.java
//
//  Created by admin on 1/26/14.
//

#include "NativeFunctions.h"

@implementation NativeFunctions

+ (float)cgrectx:(id)cgrect {
  return [(NSValue*)cgrect CGRectValue].origin.x;
}

+ (float)cgrecty:(id)cgrect {
  return [(NSValue*)cgrect CGRectValue].origin.y;
}

+ (float)cgrectw:(id)cgrect {
  return [(NSValue*)cgrect CGRectValue].size.width;
}

+ (float)cgrecth:(id)cgrect {
  return [(NSValue*)cgrect CGRectValue].size.height;
}

+ (id)cgrectmake:(float)x
               y:(float)y
               w:(float)w
               h:(float)h {
  return [NSValue valueWithCGRect:CGRectMake(x, y, w, h)];
}

- (id)init {
  return [super init];
}

@end
